version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - '80:80'
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: asp-server
    env_file:
      - ./server/.env
    environment:
      ASPNETCORE_ENVIRONMENT: 'Production'
      ASPNETCORE_URLS: 'http://+:5001'
    ports:
      - '3002:5001'
    restart: unless-stopped
